spring.application.name=Atlas // ATLAS

// POSTGRESQL CONNECTION

spring.datasource.url=jdbc:postgresql://localhost:5432/plataforma?options=-c%20TimeZone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username=plataforma_user
spring.datasource.password=plataforma_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
