spring.application.name=Atlas // ATLAS

// POSTGRESQL CONNECTION

spring.datasource.url=jdbc:postgresql://localhost:5432/plataforma
spring.datasource.username=plataforma_user
spring.datasource.password=plataforma_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
